### ISSUE TITLE
Sample for using ConfigurationBuilder as well?

### ISSUE THREAD

**Issue by tstpierre** [Azure/azure-functions-dotnet-extensions#11]
How do you handle the ConfigurationBuilder with this DI approach now that the function itself is not static, but a class getting constructor injection?

`
            var config = new ConfigurationBuilder()
                .SetBasePath(context.FunctionAppDirectory)
                .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
                .AddEnvironmentVariables()
                .Build();
`

**Comment by simonbu11** [comment]
@tstpierre I have got it working doing the following:

`builder.Services.AddSingleton<IConfiguration>(provider => new ConfigurationBuilder()
                .AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)
                .AddEnvironmentVariables()
                .Build());`

Though not sure if there is a more "official" way of doing it

**Comment by arkiaconsulting** [comment]
@tstpierre I use an extension method like this one:
```
public static class FunctionExtensions
    {
        // Workaround, waiting for Sdk improvements
        // Check https://github.com/MicrosoftDocs/azure-docs/issues/30815
        public static void ConfigureProviders(this IServiceCollection services, Action<IConfigurationBuilder> configure)
        {
            var configurationBuilder = new ConfigurationBuilder();
            var descriptor = services.FirstOrDefault(d => d.ServiceType == typeof(IConfiguration));
            if (descriptor?.ImplementationInstance is IConfiguration configRoot)
            {
                configurationBuilder.AddConfiguration(configRoot);
            }
            var config = configurationBuilder.Build();

            configure(configurationBuilder);

            config = configurationBuilder.Build();

            services.Replace(ServiceDescriptor.Singleton(typeof(IConfiguration), config));
        }
    }
```

**Comment by fabiocav** [comment]
@brettsam can you share the link to the issue you're using to track the configuration support? We should be able to close this in favor of that issue, which should also be tracking documentation and samples updates.

**Comment by brettsam** [comment]
Let's use this to track docs and samples: https://github.com/Azure/azure-functions-dotnet-extensions/issues/44
