### ISSUE TITLE
FunctionsStartup bypasses host.json

### ISSUE THREAD

**Issue by simonbu11** [Azure/azure-functions-dotnet-extensions#13]
I am just updating a small function app that was created with the VS 2017 template that uses static functions. I had updated my host.json to remove the `api` prefix:

`"extensions": {
    "http": {
      "routePrefix": ""
    }
  }`

As soon as the Startup class is annotated with `[assembly: FunctionsStartup(typeof(MyNamespace.Startup))]` it ignores this config and the prefix is added.

Should host.json be honoured in this situation or is there an alternative method to affect the api prefix?

**Comment by erik-neumann** [comment]
Same issue here, but with EventHub extension configuration in host.json. I see the IOptions<EventHubOptions> service resolving with the correct values on Startup.cs, but the Trigger actually uses defaults.

**Comment by APIWT** [comment]
This might be related: https://github.com/Azure/azure-webjobs-sdk/issues/2223

**Comment by brettsam** [comment]
Can you share your full `host.json` here? Also, what version of `Microsoft.NET.Sdk.Functions` are you using? Can you move to the latest and try again?

**Comment by simonbu11** [comment]
@brettsam I think I might have been using <1.0.28, as I have just created a new project (that targets 1.0.28) and it works OK

**Comment by brettsam** [comment]
Okay, great -- even 1.0.29 has some good bug fixes around extension discovery. I'm going to go ahead and close, but feel free to re-open if you see it again.
