### ISSUE TITLE
Load custom configuration file at startup

### ISSUE THREAD

**Issue by benspeth** [Azure/azure-functions-dotnet-extensions#17]
I have a custom configuration file called appSettings.json and, 
now that we are using dependency injection, I want to load it at startup.

before dependency injection my code looked like this:
```
    public static class Functions
    {
        private const string EveryFiveMinutesCron = "0 */5 * * * *";

        [FunctionName("MyFunction")]
        public static async Task MyFunction([TimerTrigger(EveryFiveMinutesCron)] TimerInfo myTimer, ILogger log, ExecutionContext context)
        {
            var conf = new ConfigurationBuilder()
               .SetBasePath(context.FunctionAppDirectory)
               .AddJsonFile($"appSettings.json", true, true)
               .Build();
        }
    }

```

now I want to do the same in startup, but I don't have access to the `ExecutionContext`
```
[assembly: FunctionsStartup(typeof(Startup))]

namespace MyFunctions
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var appSettings = GetAppSettings();

        }

        private IConfigurationRoot GetAppSettings()
        {
            var rootFolder = Environment.CurrentDirectory;

            var confBuilder = new ConfigurationBuilder()
                .SetBasePath(rootFolder)
                .AddJsonFile("appSettings.json", true, true);

            return confBuilder.Build();
        }
    }
}

```

I tried many ways to retrieve the `FunctionAppDirectory` property (mainly through environment variables), but none works once deployed.

How can I retrieve function app directory while at startup ?

**Comment by benspeth** [comment]
I found a working solution by using `Assembly.GetExecutingAssembly()`: 
```
[assembly: FunctionsStartup(typeof(Startup))]

namespace MyFunctions
{
    public class Startup : FunctionsStartup
    {
        public override void Configure(IFunctionsHostBuilder builder)
        {
            var binDirectory = Path.GetDirectoryName(Assembly.GetExecutingAssembly().Location);
            var rootDirectory = Path.GetFullPath(Path.Combine(binDirectory, ".."));
        }
    }
}
```

I'm wondering something, is it safe to assume that the root directory of any function app will always be "D:\home\site\wwwroot" ?

Could it be considered safe to put it as a const string in the code ?

**Comment by danhamlin** [comment]
I've gotten the app directory in the Configure method like so:
```
var executionContextOptions = builder.Services.BuildServiceProvider().GetService<IOptions<ExecutionContextOptions>>().Value;
var appDirectory = executionContextOptions.AppDirectory;
```
This works both locally and deployed to Azure.

**Comment by APIWT** [comment]
Both solutions here are very clever. Thank you!

**Comment by fabiocav** [comment]
Custom configuration is supported with the preview package published with this release: https://github.com/Azure/azure-functions-dotnet-extensions/releases/tag/v1.1.0-preview1

Package: https://www.nuget.org/packages/Microsoft.Azure.Functions.Extensions/1.1.0-preview1

You can also find some documentation on how to use the new feature here: https://github.com/Azure/azure-functions-dotnet-extensions/wiki/Configuration-and-FunctionsHostBuilderContext-support

Please try this out and provide any feedback you may have here.

**Comment by fabiocav** [comment]
Closing this as resolved, but please let us know if you have any questions. 

If you run into problems with the new functionality, please open a new issue with the details. Thanks for the patience with this!
