### ISSUE TITLE
Using GitHub Releases

### ISSUE THREAD

**Issue by marcduiker** [Azure/azure-functions-dotnet-extensions#31]
Hi @fabiocav, would you consider making [GitHub releases](https://help.github.com/en/github/administering-a-repository/creating-releases) for this extension? Then the [Azure Functions Twitterbot](https://twitter.com/az_func_updates) can tweet when new releases of this extension will become available.

Thanks! :)
Marc

**Comment by fabiocav** [comment]
@marcduiker apologies for the delay on the response. 

Yes! We'll do that moving forward. We'll also work on having a release here for the current version.
