### ISSUE TITLE
Getting error after update of SDK.Functions to 3.0.5

### ISSUE THREAD

**Issue by kuromukira** [Azure/azure-functions-dotnet-extensions#37]
It was working fine the other night until I updated `Microsoft.NET.SDK.Functions` nuget package to 3.0.4
Currently getting the error `Microsoft.Extensions.DependencyInjection.Abstractions: Unable to resolve service for type while trying to activate function`

### My Setup:
MacOS 10.15.3
.NET Core 3.1.102
Visual Studio Code
func cli 3.0.2245

### Related
As pointed out in #36 , `func start --build` can be used as an alternative. Unfortunately this isn't the case.

**Comment by MedAnd** [comment]
Hi @jeffhollan, also getting this issue and cannot wire-up DI... any help appreciated!

VisualStudio.16.Release/16.5.2+29926.136
ASP.NET and Web Tools 2019   16.5.236.49856
Azure Functions and Web Jobs Tools   16.5.236.49856

**Comment by MedAnd** [comment]
In case it helps & an update to above... seems something was screwed up with cached files in VS 2019... after doing: 

dotnet add package Microsoft.Azure.Functions.Extensions --version 1.0.0
dotnet add package Microsoft.NET.Sdk.Functions --version 3.0.5

I now do not get the error.... even though I did the same thing in VS 2019 package manager UI.

**Comment by fabiocav** [comment]
@MedAnd interesting issue.

@kuromukira are you still seeing this problem? Thanks

**Comment by kuromukira** [comment]
@fabiocav sorry for late response. At the moment no, I have not encountered the issue. Closing this issue now. Thanks.
