### ISSUE TITLE
Error "The binding type(s) 'blobTrigger' are not registered." after update of SDK.Functions to 3.0.4

### ISSUE THREAD

**Issue by mchudinov** [Azure/azure-functions-dotnet-extensions#38]
Getting en error "_The binding type(s) 'blobTrigger' are not registered. Please ensure the type is correct and the binding extension is installed._"
after update of SDK.Functions to 3.0.4.
Even a most simple setup like this fails:
```        [FunctionName("Function1")]
        public static void Run([BlobTrigger("samples-workitems/{name}", Connection = "AzureWebJobsStorage")]Stream myBlob, string name, ILogger log)
        {
            log.LogInformation($"C# Blob trigger function Processed blob\n Name:{name} \n Size: {myBlob.Length} Bytes");
        }

**Comment by hwagterveld** [comment]
Downgrading SDK.Functions to 3.0.3 fixes this problem. Still wondering why a minor version upgrade results in this error.

**Comment by mchudinov** [comment]
A new version SDK.Functions 3.0.**5** has just been shipped. It fixes this problem.
