### ISSUE TITLE
Documentation and Samples for new IWebJobsConfigurationStartup support

### ISSUE THREAD

**Issue by brettsam** [Azure/azure-functions-dotnet-extensions#44]
This is a tracking issue that will be updated with a link to documentation and samples once they are merged.

**Comment by fabiocav** [comment]
FYI, @anthonychu ; not sure if Brett has worked with you on this yet, but I'll reach out for context

**Comment by fabiocav** [comment]
This is in progress.

**Comment by brettsam** [comment]
https://docs.microsoft.com/en-us/azure/azure-functions/functions-dotnet-dependency-injection#customizing-configuration-sources

**Comment by HiroyukiSakoh** [comment]
@brettsam @fabiocav 
To prioritize AppService-Settings as well as ASP.NET Core + Web Apps, 
I think the implementation would look like this.
```
builder.ConfigurationBuilder
.AddJsonFile(Path.Combine(context.ApplicationRootPath, "appsettings.json"), optional: true, reloadOnChange: false)
.AddJsonFile(Path.Combine(context.ApplicationRootPath, $"appsettings.{context.EnvironmentName}.json"), optional: true, reloadOnChange: false)
.AddEnvironmentVariables();
```

I think the sample should be modified.

**Comment by anthonychu** [comment]
Thanks @HiroyukiSakoh. I've submitted a change to the doc sample to add environment variables last. Should be live in the next 24 hours.
