### ISSUE TITLE
When will 1.1.0 final be released?

### ISSUE THREAD

**Issue by IanKemp** [Azure/azure-functions-dotnet-extensions#50]
Really looking forward to being able to use the [new features](https://github.com/Azure/azure-functions-dotnet-extensions/wiki/Configuration-and-FunctionsHostBuilderContext-support) - how long is it necessary to keep these in preview, considering that the requisite runtime versions have long been rolled out to all Azure customers?

**Comment by jackbond** [comment]
Also waiting for non-preview release. :)

**Comment by anthonychu** [comment]
Synced with @brettsam and @fabiocav today. Should be published soon!

**Comment by fabiocav** [comment]
Assigning this to sprint 84 as a stretch goal. Sprint 84 ends tomorrow, so it's possible this will slip into the beginning of sprint 85.

**Comment by jackbond** [comment]
How long are your sprints? :)

**Comment by fabiocav** [comment]
Functions sprints are 2 weeks long. That will map to the milestone the issue is assigned to and each milestone has a due date set.

**Comment by brettsam** [comment]
I've just published it: https://www.nuget.org/packages/Microsoft.Azure.Functions.Extensions/1.1.0

**Comment by jackbond** [comment]
Awesome! Thanks.

**Comment by IanKemp** [comment]
yesssss
