### ISSUE TITLE
[Question] How to use appsetting.json values in a trigger?

### ISSUE THREAD

**Issue by MhAllan** [Azure/azure-functions-dotnet-extensions#58]
I knew we can use appsettings.json in azure function, but I don't know how can I make the trigger read the values from this file.

simply, I want the trigger to read from appsettings.development.json instead of local.settings.json because I keep switching between WebApp and Azure Function.

so I want to do this

```csharp
[CosmosDbTrigger(ConnectionStringSetting = "this values should come from appsettings.development.json" ... ]
```

**Comment by kshyju** [comment]
@MhAllan Is this in-proc app or isolated app?

**Comment by mattchenderson** [comment]
Closing as stale. But also, we do not encourage using alternative configuration providers for trigger connection configuration. See https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#configuration
