### ISSUE TITLE
Microsoft.Azure.Functions.Extensions NuGet "overrides" WebJobs.Extensions?

### ISSUE THREAD

**Issue by balivo** [Azure/azure-functions-dotnet-extensions#6]
Just asking... 

Is "Microsoft.Azure.WebJobs.Extensions" moving to "Microsoft.Azure.Functions.Extensions"?

Tks.

**Comment by fabiocav** [comment]
No. Those are different packages, with different functionality. The WebJobs extensions package is primarily for binding extensions.
