### ISSUE TITLE
[Feature Request] Specify Startup per function

### ISSUE THREAD

**Issue by tidusjar** [Azure/azure-functions-dotnet-extensions#61]
Hello,

I am wondering if it would be a good option to be able to specify or decorate a function to tell it which startup it should use.

The usecase of this is if we have a single function project which multiple functions inside, they are all related but some of these does not need any of the DI configuration some of the others have, so it would be nice to be able to provide a `FuncationAStartup` and `FunctionXStartup`.

**Comment by CasperWSchmidt** [comment]
The startup is only triggered once the application boots (upon the first invocation of any function). This ensures that the work is only done once and it shouldn't be a problem for all functions to share the same configuration. If they are more distinct than related you could split them in multiple function applications and have the shared code as a NuGet package.

**Comment by satvu** [comment]
Closing as this is not a feature we plan to add - @CasperWSchmidt has a good workaround for your scenario.
