### ISSUE TITLE
'IServiceCollection' does not contain a definition for 'AddHttpClient'

### ISSUE THREAD

**Issue by michaeljdresser** [Azure/azure-functions-dotnet-extensions#7]
Documentation and Build video show 'AddHttpClient' being used, but this doesn't  appear to be defined in in the 'IServiceCollection'.

![image](https://user-images.githubusercontent.com/28652742/57439334-b498e000-723d-11e9-8231-b98109c39885.png)

Thanks

Michael.

**Comment by rasmuschristensen** [comment]
@michaeljdresser You need Nuget Microsoft.Extensions.Http

**Comment by fabiocav** [comment]
Indeed. Closing as answered, but let us know if you continue to run into issues.
