### ISSUE TITLE
Incompatiblity with EF Core 7

### ISSUE THREAD

**Issue by Gevil** [Azure/azure-functions-dotnet-extensions#72]
Greetings,

Today I tried upgrading our .NET 6 - Functions V4 projects to use the new EF Core 7 libraries.

The resulting exception is as follows on Startup:

Microsoft.Azure.Functions.Extensions: Method not found: 'Microsoft.Extensions.Configuration.IConfigurationBuilder Microsoft.Azure.WebJobs.Hosting.IWebJobsConfigurationBuilder.get_ConfigurationBuilder()'.
Value cannot be null. (Parameter 'provider')

Package versions used:
```
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="7.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="7.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="7.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer.NetTopologySuite" Version="7.0.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="7.0.0">        
        <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.5.0" />
        <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.1" />
        <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="7.0.0" />
        <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="7.0.0" />
        <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.1.1" />
```
        
As far as we know EF Core 7 is supposed to be compatible with .NET 6 and I would expect it to be compatible with Azure Functions as well including dependency injection.

Additional information: we are running a .NET 6 Functions V4 In Process App.
The debugging already fails locally regardless of which version we try to use from the new EF Core 7 previews or the release version of the packages.

**Comment by nagarjunacspeaks** [comment]
We are facing same issue.

**Comment by christianacca** [comment]
As are we

**Comment by bahiyah** [comment]
We are facing the same issue too.

**Comment by jasonni0** [comment]
Same issue too.

**Comment by danielgreen** [comment]
Hit the same issue. The latest Azure Functions runtime 4.30.0 loads versions of some libraries that are older than the versions referenced by EF7.

There seems to be scant information available on the runtime versions - are they visible in any public repo or MS docs page?
They don't correspond to the versions of Azure Functions Core Tools that can be installed via MSI.

cc @cloudmelon

**Comment by mtucker6784** [comment]
Apologies for bumping, but has there been a resolution to this thread?

**Comment by collinbarrett** [comment]
If it's helpful, I _think_ this issue only applies to the In-process model. EF Core 7 works without this error in the Isolated model. Since Isolated is the future of Azure Functions, I doubt that resolving this for In-process will get much attention.

**Comment by dlstaylor91** [comment]
same issue - azure functions and their dependency structures are a nightmare

**Comment by jamesonhill** [comment]
Has anyone found a workaround?

**Comment by balivo** [comment]
Yes... Stop use Azure Functions!

**Comment by dlstaylor91** [comment]
Indeed, the prescribed resolution is to operate your Azure functions in an out-of-process (isolated) mode. This strategy provides a segregation between the function host and the worker processes, subsequently enabling access to more recent libraries.

Transitioning from an in-process to an out-of-process architecture can be a complex process, particularly for expansive applications. Certain factors need to be meticulously evaluated prior to initiating the migration as the current state of function execution in out-of-process mode lacks full feature equivalence with its in-process counterpart.

From the information I've gathered, it appears that the Azure Functions team is actively addressing this disparity. It is reasonable to anticipate increased alignment between the two execution modes in upcoming .NET releases.

**Comment by Gevil** [comment]
> 

Yep that seems to be what is going on.

We recently tried to switch over to out of process isolated functions to discover that we can not bind to the ServiceBus message object in our batch triggers because the functionality was not there yet so we had to stay on .net6 with our functions and using EF Core 6 as well.

Such basic functionality should really be prioritized higher when trying to force us over to new ways of infra/runtimes/sdks etc.

So in essence we are stuck with .net6 until hopefully these things are solved and implemented properly in Functions Isolated and .NET 8 maybe.

**Comment by fabiocav** [comment]
I'm sorry about the delayed response to the issues in this repo.

As mentioned by a few here, a lot of work has gone into closing gaps between the in-proc and out-of-proc models, and we're now at a point where we have functional/feature parity between the two. 

Our recommendation, particularly if moving to dependencies ahead of the .NET 6 dependencies unified by the host (or targeting .NET 7+) is to move to the isolated model.

I'm closing this issue as answered, but if you run into problems with that process, please open an issue at https://github.com/Azure/azure-functions-dotnet-worker/issues

Thank you for engaging and for the patience here.
