### ISSUE TITLE
Is there any documentation available for migrating from IWebJobsStartup to FunctionsStartup in Azure Function?

### ISSUE THREAD

**Issue by prashantagrawalcrowe** [Azure/azure-functions-dotnet-extensions#74]
Hi,

Please let me know if there is any official documentation available for migrating startup class from IWebJobsStartup to FunctionsStartup in Azure Function?

Thanks
Prashant

**Comment by fabiocav** [comment]
Hey @prashantagrawalcrowe, no documentation for that topic specifically, but if you're running into issues, we can provide some guidance here if you can share the details.

**Comment by udlose** [comment]
> Hey @prashantagrawalcrowe, no documentation for that topic specifically, but if you're running into issues, we can provide some guidance here if you can share the details.

@fabiocav I'm using an Isolated Worker Function (v4). I see that the [DI Sample here](https://github.com/Azure/azure-functions-dotnet-extensions/blob/main/src/samples/DependencyInjection/Basic/SampleStartup.cs) uses `FunctionStartup` yet everything I can find on setting up DI/Configuration for Isolated Worker says you cannot use `FunctionStartup`.  Is that still the case? Should the sample be updated?

**Comment by mattchenderson** [comment]
Closing old item. The documentation for configuring DI in the isolated worker model as part of your `Program.cs` file is found here: https://learn.microsoft.com/en-us/azure/azure-functions/dotnet-isolated-process-guide?tabs=windows#start-up-and-configuration
