### ISSUE TITLE
Support for other DI containers, e.g. AutoFac

### ISSUE THREAD

**Issue by AdrianPell** [Azure/azure-functions-dotnet-extensions#9]
My functions app is part of a wider solution that already uses Autofac for dependency injection … and was using Autofac DI through one of the earlier workarounds.

How would I set about using Autofac from the new supported DI structure? Other places that use Microsoft.Extensions.DependencyInjection.Abstractions seems to support switching the DI container.

**Comment by srozga** [comment]
Our ASP.Net Core application is composed of multiple Autofac Modules. We have a new requirement to create a Function that uses much of the same code. Would be easier to manage dependencies by reusing some of the existing Autofac modules. +1 on this one.

**Comment by AdrianPell** [comment]
@jeffhollan Any thoughts on this one?

**Comment by fabiocav** [comment]
This is not currently supported or planned. There is some future work that may enable some of these capabilities, but that is not in the immediate roadmap.
